# Generated by Django 3.0 on 2020-12-19 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_activity_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='activity',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
