# Generated by Django 3.0 on 2021-01-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201222_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='updated_at',
        ),
    ]
